name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build Hugo site
        run: |
          sudo apt-get install hugo -y
          hugo --minify

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token "$FIREBASE_TOKEN"
