name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'           # Changed to latest instead of specific version
          extended: true                    # Keep this for proper PaperMod compatibility

      - name: Build site                   # Renamed for clarity
        run: |
          hugo mod graph                  # New Hugo command to check module dependencies
          hugo --minify

      - name: Deploy to GitHub Pages       # Updated deployment command
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
